#!/bin/sh
# Registers the Readmill native host with every Chromium-family browser found.
# Re-run it after moving this folder or changing Node versions.
#   READMILL_DIR=~/somewhere ./install.sh   to store comments somewhere other than ~/notes/web-comments
set -eu

HOST_NAME="com.readmill.host"
EXT_ID="eagekkfdfbhiacmlocmonbekoicokhlj" # fixed by the "key" in extension/manifest.json
ROOT=$(cd "$(dirname "$0")" && pwd)
NODE=$(command -v node || true)
DATA_DIR="${READMILL_DIR:-$HOME/notes/web-comments}"

if [ -z "$NODE" ]; then
  echo "node not found on PATH; install Node.js first" >&2
  exit 1
fi

# Chrome launches the host with a bare environment, so pin node and the data folder here.
LAUNCHER="$ROOT/host/readmill-host"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by install.sh
export READMILL_DIR="$DATA_DIR"
exec "$NODE" "$ROOT/host/readmill-host.js" "\$@"
EOF
chmod +x "$LAUNCHER" "$ROOT/host/readmill-host.js"

MANIFEST=$(cat <<EOF
{
  "name": "$HOST_NAME",
  "description": "Readmill comment storage",
  "path": "$LAUNCHER",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF
)

case "$(uname)" in
  Darwin)
    S="$HOME/Library/Application Support"
    DIRS="$S/Google/Chrome
$S/Google/Chrome Beta
$S/Google/Chrome Canary
$S/Chromium
$S/BraveSoftware/Brave-Browser
$S/Microsoft Edge
$S/Arc/User Data
$S/Vivaldi" ;;
  *)
    C="${XDG_CONFIG_HOME:-$HOME/.config}"
    DIRS="$C/google-chrome
$C/google-chrome-beta
$C/chromium
$C/BraveSoftware/Brave-Browser
$C/microsoft-edge
$C/vivaldi" ;;
esac

echo "$DIRS" | while IFS= read -r d; do
  [ -d "$d" ] || continue
  mkdir -p "$d/NativeMessagingHosts"
  printf '%s\n' "$MANIFEST" > "$d/NativeMessagingHosts/$HOST_NAME.json"
  echo "registered with: $d"
done

mkdir -p "$DATA_DIR"
echo
echo "Comments will be saved in: $DATA_DIR"
echo "Check: $LAUNCHER pages"
echo
echo "Next, if you haven't: chrome://extensions → Developer mode → Load unpacked → $ROOT/extension"
